#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Motor,  motorA,          irArm,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     rightWheel,    tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S4_C1_2,     leftWheel,     tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S4_C2_1,     pulley1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     pulley2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     motorzzz,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     collector1,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C4_1,    Lock,                 tServoStandard)
#pragma config(Servo,  srvo_S4_C4_2,    Asshole,              tServoStandard)
#pragma config(Servo,  srvo_S4_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_6,    Center,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*  COMPLETE
 *	Author: 	Markus Feng, Alex Guo, William Ughetta
 *	Team: 	DA Robotics
 *	Project: 	Cascade Effect 2014
 * 	Program: 	Robot Controller
 *	Date: 2015
 */


#include "JoystickDriver.c"
#include "hitechnic-irseeker-v2.h"

const int minSpeed = 5;
const int maxSpeed = 100;

float absSqrt(float input){
	if(input < 0){
		return -sqrt(-input);
	}
	else{
		return sqrt(input);
	}
}

short getWheelSpeed(int controllerSpeed) {
		if(controllerSpeed > maxSpeed) {
				return maxSpeed;
			}
			else if(controllerSpeed < -maxSpeed) {
				return -maxSpeed;
			}
			else if(controllerSpeed > minSpeed) {
				return controllerSpeed / 4; //slower
			}
			else if(controllerSpeed < minSpeed * -1) {
				return controllerSpeed / 6; //even slower going backwards
			}
			else {
				return 0;
			}
}

int maxServo = 255;
int minServo = 0;

bool b;
bool lockOn = false;
bool lockDown = false;
bool holderOpen = false;
bool holderDown = false;

task main() {
		//waitForStart(); //Enable for competition

		short basej1_y2 = joystick.joy1_y2;
		short basej1_y1 = joystick.joy1_y1;

		short basej2_y2 = joystick.joy2_y2;
		short basej2_y1 = joystick.joy2_y1;

		servo[Lock] = 0;
		servo[servo2] = 140;

		while(true) {
			getJoystickSettings(joystick); //poll for joystick activity

			int y2 = (joystick.joy1_y2 - basej1_y2);
			int y1 = (joystick.joy1_y1 - basej1_y1);

			int y2x = (joystick.joy2_y2 - basej2_y2);
			int y1x = (joystick.joy2_y1 - basej2_y1);

			int rightSpeed = getWheelSpeed(y2);
			int leftSpeed = getWheelSpeed(y1);

			rightSpeed = absSqrt(rightSpeed)*10;
			leftSpeed = absSqrt(leftSpeed)*10;

			//if(joy1Btn(8) == 1){
			//		rightSpeed = rightSpeed / 2;
			//		leftSpeed = leftSpeed / 2;
			//}
			motor[rightWheel] = rightSpeed;
			motor[leftWheel]  = -leftSpeed;
			if(joy1Btn(8) == 1){
				motor[collector1] = maxSpeed*0.5;
			}
			else if(joy1Btn(6) == 1){
				motor[collector1] = maxSpeed*0.1;
			}
			else{
				motor[collector1] = 0;
			}

			if(joy1Btn(5) == 1){
				motor[pulley1] = maxSpeed;
				motor[pulley2] = -maxSpeed;
			}
			else if(joy1Btn(7) == 1){
				motor[pulley1] = -maxSpeed;
				motor[pulley2] = maxSpeed ;
			}
			else{
				if(joy2Btn(5) == 1){
				  	motor[pulley1] = maxSpeed;
				}
				else if(joy2Btn(7) == 1){
				   	motor[pulley1] = -maxSpeed;
				}
				else{
						motor[pulley1] = 0;
				}

				if(joy2Btn(6) == 1){
					motor[pulley2] = -maxSpeed;
				}
				else if(joy2Btn(8) == 1){
					motor[pulley2] = maxSpeed ;
				}
				else{
					motor[pulley2] = 0;
				}
			}

			if(joy2Btn(2) == 1){
				motor[irArm] = 5;
			}
			else if(joy2Btn(3) == 1){
				motor[irArm] = -5;
			}
			else{
				motor[irArm] = 0;
			}
			if(joy1Btn(4) == 1){
			servo[Center] = 70;
			}
			else if(joy1Btn(1) == 1){
			servo[Center] = 125;
			}
			if(!lockDown && joy1Btn(2) == 1){
					lockOn = !lockOn;
					if(lockOn){
						servo[Lock] = 190;
					}
					else{
						servo[Lock] = 0;
					}
					lockDown = true;
			}
			if(joy1Btn(2) == 0){
				lockDown = false;
			}
			if(!holderDown && joy1Btn(3) == 1){
					holderOpen = !holderOpen;
					if(holderOpen){
						servo[servo2] = 180;
					}
					else{
						servo[servo2] = 140;
					}
					holderDown = true;
			}
			if(joy1Btn(3) == 0){
				holderDown = false;
			}
			int ac1, ac2, ac3, ac4, ac5 = 0;
			int acx=0;
	HTIRS2readAllACStrength(HTIRS2, ac1, ac2, ac3, ac4, ac5);
	nxtDisplayTextLine(0, "%d", ac1);
	nxtDisplayTextLine(1, "%d", ac2);
	nxtDisplayTextLine(2, "%d", ac3);
	nxtDisplayTextLine(3, "%d", ac4);
	nxtDisplayTextLine(4, "%d", ac5);
	acx = HTIRS2readACDir(HTIRS2);
	nxtDisplayTextLine(5, "%d", acx);
		}
}
