#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     irSensor,       sensorAnalog)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S4_C1_1,     rightWheel,    tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S4_C1_2,     leftWheel,     tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S4_C2_1,     pulley1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     pulley2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     collector1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Seemingly Unnecessary
#pragma config(Motor,  motorA,          clawFrontRight, tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          clawSide,      tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          clawFrontLeft, tmotorNXT, openLoop)
*/
/*
 *	Author: 	Markus Feng, Alex Guo, William Ughetta
 *	Team: 	DA Roboticss
 *	Project: 	Cascade Effect 2014
 * 	Program: 	Robot Controller
 *	Date: 2015
 */


/*
#pragma config(Servo,  srvo_S4_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_6,    servo6,               tServoNone)
*/

#include "JoystickDriver.c"

const int minSpeed = 5;
const int maxSpeed = 100;

float absSqrt(float input){
	if(input < 0){
		return -sqrt(-input);
	}
	else{
		return sqrt(input);
	}
}

short getWheelSpeed(int controllerSpeed) {
		if(controllerSpeed > maxSpeed) {
				return maxSpeed;
			}
			else if(controllerSpeed < -maxSpeed) {
				return -maxSpeed;
			}
			else if(controllerSpeed > minSpeed) {
				return controllerSpeed / 4; //slower
			}
			else if(controllerSpeed < minSpeed * -1) {
				return controllerSpeed / 6; //even slower going backwards
			}
			else {
				return 0;
			}
}

task main() {
		//waitForStart(); //Enable for competition

		short basej1_y2 = joystick.joy1_y2;
		short basej1_y1 = joystick.joy1_y1;

		while(true) {
			getJoystickSettings(joystick); //poll for joystick activity

			int y2 = (joystick.joy1_y2 - basej1_y2);
			int y1 = (joystick.joy1_y1 - basej1_y1);

			int rightSpeed = getWheelSpeed(y2);
			int leftSpeed = getWheelSpeed(y1);

			rightSpeed = absSqrt(rightSpeed)*10;
			leftSpeed = absSqrt(leftSpeed)*10;

			//if(joy1Btn(8) == 1){
			//		rightSpeed = rightSpeed / 2;
			//		leftSpeed = leftSpeed / 2;
			//}
			motor[rightWheel] = rightSpeed;
			motor[leftWheel]  = -leftSpeed;

			/*
			if(joy1Btn(5) == 1){
				motor[pulley1] = maxSpeed;
			}
			else if(joy1Btn(7) == 1){
				motor[pulley1] = -maxSpeed;
			}
			else{
				motor[pulley1] = 0;
			}
			if(joy1Btn(8) == 1){
				motor[pulley2] = maxSpeed;
			}
			else if(joy1Btn(6) == 1){
				motor[pulley2] = -maxSpeed;
			}
			else{
				motor[pulley2] = 0;
			}
			*/
			if(joy1Btn(5) == 1){
				motor[pulley1] = maxSpeed;
				motor[pulley2] = -maxSpeed;
			}
			else if(joy1Btn(7) == 1){
				motor[pulley1] = -maxSpeed;
				motor[pulley2] = maxSpeed;
			}
			else{
				motor[pulley1] = 0;
				motor[pulley2] = 0;
			}
		}
}


/* Unnecessary:

		/*
			 * Descritption: Right Wheel Drive
		   * 	Controller: Right Joystick Y
			 *
			if(y2 > maxSpeed) {
				rightSpeed = maxSpeed;
			}
			else if(y2 < -maxSpeed) {
				rightSpeed = -maxSpeed;
			}
			else if(y2 > minSpeed) {
				rightSpeed = y2 / 4; //slower
			}
			else if(y2 < minSpeed * -1) {
				rightSpeed = y2 / 6; //even slower going backwards
			}
			else {
				rightSpeed = 0;
			}

			/*
			 * Descritption: Left Wheel Drive
			 * 	Controller: Left Joystick Y
			 *
			if(y1 > maxSpeed) {
				leftSpeed = maxSpeed;
			}
			else if(y1 < -maxSpeed) {
				leftSpeed = -maxSpeed;
			}
			else if(y1 > minSpeed) {
				leftSpeed = y1 / 4; //slower
			}
			else if(y1 < minSpeed * -1) {
				leftSpeed = y1 / 6; //even slower going backwards
			}
			else {
				leftSpeed = 0;
			}
*/
